name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Instala pnpm globalmente
      - name: Install pnpm
        run: npm install -g pnpm
        
      # Configura Node.js com pnpm
      - name: Set up Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      

      # Backend
      - name: Install Backend Dependencies
        working-directory: ./server
        run: pnpm install  # Alterado para pnpm

      - name: Start Backend
        working-directory: ./server
        run: pnpm run dev &  # Alterado para pnpm
        env:
          NODE_ENV: test
          MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
          PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
          PAYPAL_CLIENT_SECRET: ${{ secrets.PAYPAL_CLIENT_SECRET }}
          CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}

      # Frontend
      - name: Install Frontend Dependencies
        working-directory: ./client
        run: pnpm install  # Alterado para pnpm

      - name: Start Frontend
        working-directory: ./client
        run: pnpm run dev &  # Alterado para pnpm
        env:
          NODE_ENV: test
          VITE_API_URL: http://localhost:5000

      # Espera pelos servidores
      - name: Wait for Servers
        run: |
          npx wait-on http://localhost:5000
          npx wait-on http://localhost:5173

      # Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./client
          start: pnpm run test  # Alterado para pnpm
          wait-on: 'http://localhost:5173'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}